name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptopenjdk'  # You can use 'zulu', 'adoptopenjdk', 'openjdk', etc.
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
